// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClipVideo() {
  return window['go']['main']['App']['ClipVideo']();
}

export function DownloadVideo(arg1) {
  return window['go']['main']['App']['DownloadVideo'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}
